[book]
title = "Kalei Compiler Documentation"
authors = ["Milo Moisson"]
language = "en"

[preprocessor.treesitter]
command = "mdbook-treesitter"
languages = [
  "kalei",
  "rust",
]

[output.html]
git-repository-url = "https://github.com/mrnossiom/kaleic/tree/main/docs"
edit-url-template = "https://github.com/mrnossiom/kaleic/edit/main/docs/{path}"
