name: Build and deploy the compiler rust docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "docs"
  cancel-in-progress: false

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: kalei-rust-docs
      url: https://rust-docs.kalei.wiro.world
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build .#rust-docs

      - run: |
          nix run .#git-pages-cli -- \
            https://rust-docs.kalei.wiro.world \
            --password "${GIT_PAGES_CHALLENGE}" \
            --server grebedoc.dev \
            --upload-dir result
        env:
          GIT_PAGES_CHALLENGE: ${{ secrets.GIT_PAGES_CHALLENGE }}
